// 'use client';

// import { useFormContext } from 'react-hook-form';

// import Select from '@/components/common/Select';
// import Input from '@/components/ui/Input';
// import { useCategories } from '@/features/categories/api/queries';

// export default function BasicInfoStep() {
//   const {
//     register,
//     formState: { errors },
//   } = useFormContext();

//   const { data: categoryData, isLoading: isLoadingCategories } = useCategories({
//     status: 'PUBLISHED',
//     limit: 100,
//   });
//   const rawCategories = categoryData?.categories || [];
//   const categoriesList = rawCategories.filter((c: any) => c.status === 'PUBLISHED');

//   return (
//     <div className="space-y-8">
//       {/* Heading */}
//       <div>
//         <h2 className="text-xl font-semibold">Basic Information</h2>
//         <p className="mt-1 text-sm text-text-light">Fill in the basic tender details.</p>
//       </div>

//       {/* Tender Title */}
//       <div>
//         <label className="mb-2 block text-sm font-medium">
//           Tender Title <span className="text-red-500">*</span>
//         </label>

//         <Input
//           type="text"
//           placeholder="Annual IT Infrastructure Maintenance 2026"
//           {...register('title', {
//             required: 'Tender title is required.',
//             minLength: {
//               value: 5,
//               message: 'Minimum 5 characters required.',
//             },
//           })}
//         />

//         {errors.title && (
//           <p className="mt-1 text-sm text-red-500">{errors.title.message as string}</p>
//         )}
//       </div>

//       {/* Reference + Budget */}
//       <div className="grid gap-6 md:grid-cols-2">
//         <div>
//           <label className="mb-2 block text-sm font-medium">Tender Reference</label>

//           <Input readOnly {...register('referenceNumber')} />

//           <p className="mt-1 text-xs text-text-light font-normal leading-normal">
//             Auto-generated by the system.
//           </p>
//         </div>

//         <div>
//           <label className="mb-2 block text-sm font-medium">Estimated Budget</label>

//           <div className="grid grid-cols-[1fr_auto_1fr] gap-3">
//             <Input type="number" placeholder="Minimum" {...register('budgetMin')} />

//             <div className="flex items-center justify-center text-text-light">—</div>

//             <Input type="number" placeholder="Maximum" {...register('budgetMax')} />
//           </div>
//         </div>
//       </div>

//       {/* Tender Type + Currency */}
//       <div className="grid gap-6 md:grid-cols-2">
//         <div>
//           <label className="mb-2 block text-sm font-medium">
//             Tender Type <span className="text-red-500">*</span>
//           </label>

//           <Select
//             className="w-full"
//             {...register('tenderType', {
//               required: 'Tender type is required.',
//             })}
//           >
//             <option value="">Select Tender Type</option>
//             <option value="Open">Open Tender</option>
//             <option value="Limited">Limited Tender</option>
//             <option value="Single">Single Tender</option>
//             <option value="Global">Global Tender</option>
//           </Select>

//           {errors.tenderType && (
//             <p className="mt-1 text-sm text-red-500">{errors.tenderType.message as string}</p>
//           )}
//         </div>

//         <div>
//           <label className="mb-2 block text-sm font-medium">Currency</label>

//           <Select className="w-full" {...register('currency')}>
//             <option value="INR">INR (₹)</option>
//             <option value="USD">USD ($)</option>
//             <option value="EUR">EUR (€)</option>
//           </Select>
//         </div>
//       </div>

//       {/* Category */}
//       <div>
//         <label className="mb-2 block text-sm font-medium">
//           Category <span className="text-red-500">*</span>
//         </label>

//         <Select
//           className="w-full"
//           disabled={isLoadingCategories}
//           {...register('category', {
//             required: 'Category is required.',
//           })}
//         >
//           <option value="">
//             {isLoadingCategories ? 'Loading Categories...' : 'Select Category'}
//           </option>
//           {categoriesList.map((cat: any) => (
//             <option key={cat.id} value={cat.id}>
//               {cat.name}
//             </option>
//           ))}
//         </Select>

//         {errors.category && (
//           <p className="mt-1 text-sm text-red-500">{errors.category.message as string}</p>
//         )}
//       </div>

//       {/* Description */}
//       <div>
//         <label className="mb-2 block text-sm font-medium">
//           Tender Description <span className="text-red-500">*</span>
//         </label>

//         <textarea
//           rows={7}
//           placeholder="Provide a detailed description of the tender..."
//           className="w-full rounded-xl border border-border bg-surface px-4 py-3 outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/20 text-text font-normal leading-normal"
//           {...register('description', {
//             required: 'Tender description is required.',
//             minLength: {
//               value: 20,
//               message: 'Description should be at least 20 characters.',
//             },
//           })}
//         />

//         {errors.description && (
//           <p className="mt-1 text-sm text-red-500">{errors.description.message as string}</p>
//         )}
//       </div>
//     </div>
//   );
// }
